name: 'Terraform Azure Infrastructure'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Set the working directory to the parent folder containing main.tf
    defaults:
      run:
        working-directory: ./parent

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      # Azure Login
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: >
          {
            "clientId":"${{ secrets.ARM_CLIENT_ID }}",
            "clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}",
            "subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}",
            "tenantId":"${{ secrets.ARM_TENANT_ID }}"
          }

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.15.6

    # Verify formatting of Terraform configuration files
    - name: Terraform Format
      run: terraform fmt -check -recursive

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, etc.
    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

    # On push to "main", build or change infrastructure
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
